name: Custom Release Tag and Publish

on:
  workflow_dispatch: # Manual triggering

jobs:
  create_and_publish_release:
    name: Create and Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for tags to be accessible
  
      - name: List Tags
        run: git tag --list  # List all tags in the repository
  
      - name: Set old tag
        id: set_old_tag
        run: |
          echo "::set-output name=old_tag::$(git describe --tags --abbrev=0)"
  
      - name: Debug Old Tag
        run: |
          echo "Old Tag: ${{ steps.set_old_tag.outputs.old_tag }}"

      - name: Set new tag name
        id: set_new_tag_name
        run: echo "::set-output name=new_tag_name::TEST-DEV_$(date +'%dth-%b_%H-%M%p')"

      - name: Debug Information
        run: |
          echo "Old Tag: ${{ steps.set_old_tag.outputs.old_tag }}"
          echo "New Tag: ${{ steps.set_new_tag_name.outputs.new_tag_name }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository Name: ${{ github.repository }}"
          echo "GitHub Token: ${{ secrets.GH_TOKEN }}"

      - name: Create new tag from old tag
        run: git tag ${{ steps.set_new_tag_name.outputs.new_tag_name }} ${{ steps.set_old_tag.outputs.old_tag }}

      - name: Push new tag to repository
        run: git push origin ${{ steps.set_new_tag_name.outputs.new_tag_name }}

      - name: Generate Release Notes
        id: generate_release_notes
        uses: actions/github-script@v4
        with:
          script: |
            const compareCommits = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "${{ steps.set_old_tag.outputs.old_tag }}",
              head: "${{ steps.set_new_tag_name.outputs.new_tag_name }}",
            });

            let releaseNotes = "### Changes since " + "${{ steps.set_old_tag.outputs.old_tag }}" + ":\n\n";
            for (const commit of compareCommits.data.commits) {
              releaseNotes += "- " + commit.commit.message + "\n";
            }

            console.log(releaseNotes);

            return releaseNotes;

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.set_new_tag_name.outputs.new_tag_name }}
          release_name: Release ${{ steps.set_new_tag_name.outputs.new_tag_name }}
          body: ${{ steps.generate_release_notes.outputs.result }}
          draft: false
          prerelease: false
